[build]
  # No base directory — we cd into frontend in the command
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/build"

[build.environment]
  REACT_APP_API_BASE = "https://weatheryzer.onrender.com"
  # If you want to keep building even with warnings:
  CI = "false"

